### ISSUE TITLE
missing file(s)

### ISSUE THREAD

**Issue by amityk77** [abainbridge/deadfrog-lib#3]
Hello... cannot find "df_input" (.h/.cpp) files...

**Comment by abainbridge** [comment]
They were removed as part of the work to add Linux support. The contents are now in df_window.h and the various df_window.cpp variants.

**Comment by amityk77** [comment]
ok... there is another project "sound shovel", which requires this library... in that, we have "#include df_input.h" and also
 "#include df_window.h".  commenting "df_input.h" does not work, it produces more compile errors...

**Comment by amityk77** [comment]
I guess this issue should be shifted to "sound shovel" repo.

**Comment by amityk77** [comment]
after making changes, this is final result output, which cannot be resolved:

1>------ Build started: Project: sound_shovel, Configuration: Debug x64 ------
1>gui_base.cpp
1>k:\research.3\ss\sound_shovel\src\df_lib_plus_plus\gui\gui_base.cpp(54): error C3861: 'FontCreate': identifier not found
1>k:\research.3\ss\sound_shovel\src\df_lib_plus_plus\gui\gui_base.cpp(55): warning C4311: 'type cast': pointer truncation from 'DfFont *' to 'int'
1>k:\research.3\ss\sound_shovel\src\df_lib_plus_plus\gui\gui_base.cpp(55): warning C4302: 'type cast': truncation from 'DfFont *' to 'int'
1>main.cpp
1>k:\research.3\ss\sound_shovel\src\main.cpp(29): error C3861: 'FontCreate': identifier not found

**Comment by abainbridge** [comment]
Ah, I see. This issue should really be in the Sound Shovel project. The Sound Shovel is abandonware but most of the fixes were easy, so I just did them and pushed to the Sound Shovel repo. I've left a todo in the keyboard shortcut mechanism which is harder to fix (this is another consequence of the Linux port of DF lib). Hopefully it is good enough start for you.

**Comment by abainbridge** [comment]
The problem is that the DF lib API changed and Sound Shovel didn't keep up. I don't want to make any changes to DF lib to solve this problem.

**Comment by amityk77** [comment]
great...  i'll look into it... and further issues will be posted there... 

Thanks for your prompt replies...
