### ISSUE TITLE
"Official" way to build Linux port?

### ISSUE THREAD

**Issue by tkchia** [abainbridge/deadfrog-lib#4]
Good day @abainbridge,

May I know what the "official" way to build the Linux port for this project is?  I am currently using
```
cd build/linux
make
cd ../../examples/build/linux
make
```
but this does not work "out of the box", so I wonder if I might be missing something.

Thank you!

**Comment by abainbridge** [comment]
I don't often build on Linux, so it had rotted, sorry! The method you describe looks good. I've just pushed the fixes I needed to get it to work on my machine. Please pull and try again. Thanks for the interest...

**Comment by tkchia** [comment]
Hello @abainbridge,

Thank you.  May I also know if you accept pull requests for this project, for bug fixes and/or adding features?

**Comment by abainbridge** [comment]
Certainly yes to bug fixes. For adding features, maybe. What have you got in mind?

**Comment by tkchia** [comment]
Hello @abainbridge,

Thanks.  I am thinking of maybe adding support for the Linux frame buffer device (e.g. `/dev/fb0`), when the library is used outside of an X Window environment.

Thank you!

**Comment by abainbridge** [comment]
Yes, that would be the kind of thing I'd like to include. Generally I want to keep the code as simple as possible and not have any external dependencies except for the C standard library.

**Comment by tkchia** [comment]
Thanks @abainbridge !
